name: Test ML Toolkit actions
on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dbx
        shell: bash
        run: |
          pip install databricks-cli
          pip install dbx

      - name: setup_env_vars
        id: setup_env_vars
        shell: bash
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

      - name: Deploy
        id: deploy
        shell: bash
        run: |
          dbx deploy \
            --deployment-file="conf.yml" \
            --write-specs-to-file="deploy_spec.json"

      - name: Get job name and id
        id: get_job_name_and_id
        shell: bash
        run: |
          job_name=$(
            yq eval '.default.workflows[].name' "deploy_spec.json"
          )
          job_id=$(
            yq eval '.default.workflows[].job_id' "deploy_spec.json"
          )
          echo "$job_name"
          echo "job_name=$job_name" >> $GITHUB_OUTPUT
          echo $job_id
          echo "job_id=$job_id" >> $GITHUB_OUTPUT

      - name: echo_github_outputs
        id: echo_github_outputs
        shell: bash
        run: |
          echo "job_name: ${{ steps.get_job_name_and_id.outputs.job_names }}"
          echo "job_id: ${{ steps.get_job_name_and_id.outputs.job_ids }}"
