name: Test ML Toolkit actions
on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dbx
        shell: bash
        run: |
          pip install databricks-cli
          pip install dbx

      - name: setup_env_vars
        id: setup_env_vars
        shell: bash
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV

      - name: Deploy
        id: deploy
        shell: bash
        run: |
          dbx deploy \
            --deployment-file="conf.yml" \
            --write-specs-to-file="deploy_spec.json"

      - name: Get job name and id
        id: get_job_name_and_id
        shell: bash
        run: |
          job_names=$(
              yq --output-format=p eval '.default.workflows[].name' "deploy_spec.json"
          )
          job_ids=$(
              yq --output-format=p eval '.default.workflows[].job_id' "deploy_spec.json"
          )
          echo "$job_names"
          echo "job_names=$job_names" >> $GITHUB_OUTPUT
          echo $job_ids
          echo "job_ids=$job_ids" >> $GITHUB_OUTPUT

      - name: echo_github_outputs
        id: echo_github_outputs
        shell: bash
        run: |
          echo "job_names: ${{ steps.get_job_name_and_id.outputs.job_names }}"
          echo "job_ids: ${{ steps.get_job_name_and_id.outputs.job_ids }}"
